name: "Terraform Create & Destroy"

on:
  push:
    branches:
      - main

jobs:
  terraform-lifecycle:
    name: "Ciclo de Vida Completo"
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply (Crear)
        run: terraform apply -auto-approve

      - name: Pausa para verificar (60 segundos)
        run: |
          echo "El bucket ha sido creado. Tienes 60 segundos para verlo en AWS console."
          sleep 60

      - name: Terraform Destroy (Limpiar)
        if: always()
        run: terraform destroy -auto-approve